# Generated by Django 5.0.6 on 2026-06-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_image_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
